# Documentation: http://docs.travis-ci.com/user/languages/julia/
language: julia
os:
  - linux
  - osx
julia:
  - 1.0.3
notifications:
  email: false
matrix:
  allow_failures:
    - os: osx
    - julia: nightly
# uncomment the following lines to override the default test script
script:
        - julia -e 'import Pkg; Pkg.add("Pkg"); Pkg.add("Test");using Pkg; Pkg.test("PseudoArcLengthContinuation"; coverage=true)'   
after_success:
# push coverage results to Codecov and Coveralls
  - julia -e 'using Pkg; Pkg.add("Coverage"); using Coverage; Codecov.submit(Codecov.process_folder()); Coveralls.submit(Coveralls.process_folder())'
  - julia -e 'using Pkg; ps=PackageSpec(name="Documenter", version="0.19"); Pkg.add(ps); Pkg.pin(ps)'
  - julia -e 'using Pkg;cd(Pkg.dir("PseudoArcLengthContinuation")); include(joinpath("docs", "make.jl"))'
